# Generated by Django 5.0.6 on 2025-04-02 18:07

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="topic",
            options={},
        ),
        migrations.RenameField(
            model_name="topic",
            old_name="date_created",
            new_name="created_at",
        ),
        migrations.RenameField(
            model_name="topic",
            old_name="date_modified",
            new_name="updated_at",
        ),
        migrations.RemoveField(
            model_name="topic",
            name="description",
        ),
        migrations.AddField(
            model_name="topic",
            name="content",
            field=models.TextField(default=""),
        ),
        migrations.AlterField(
            model_name="topic",
            name="title",
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name="topic",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL
            ),
        ),
        migrations.CreateModel(
            name="RevisionSchedule",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("scheduled_date", models.DateField()),
                ("completed", models.BooleanField(default=False)),
                ("postponed", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "topic",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="api.topic"
                    ),
                ),
            ],
            options={
                "ordering": ["scheduled_date"],
            },
        ),
    ]
