# Generated by Django 5.1.7 on 2025-07-13 23:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0002_alter_topic_options_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="topic",
            name="estimated_time",
            field=models.IntegerField(
                default=30, help_text="Estimated study time in minutes"
            ),
        ),
        migrations.AddField(
            model_name="topic",
            name="priority",
            field=models.CharField(
                choices=[("low", "Low"), ("medium", "Medium"), ("high", "High")],
                default="medium",
                max_length=10,
            ),
        ),
        migrations.AddField(
            model_name="topic",
            name="status",
            field=models.CharField(
                choices=[
                    ("to_study", "To Study"),
                    ("in_progress", "In Progress"),
                    ("completed", "Completed"),
                ],
                default="to_study",
                max_length=15,
            ),
        ),
    ]
