# Generated by Django 5.1.7 on 2025-07-14 08:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0003_topic_estimated_time_topic_priority_topic_status"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="topic",
            name="estimated_time",
        ),
        migrations.RemoveField(
            model_name="topic",
            name="priority",
        ),
        migrations.RemoveField(
            model_name="topic",
            name="status",
        ),
    ]
