# Generated by Django 5.1.7 on 2025-07-15 19:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0004_remove_topic_estimated_time_remove_topic_priority_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="topic",
            name="resource_url",
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
    ]
