# Generated by Django 5.1.7 on 2025-07-15 20:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0005_topic_resource_url"),
    ]

    operations = [
        migrations.AlterField(
            model_name="revision",
            name="topic",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="legacy_revisions",
                to="api.topic",
            ),
        ),
        migrations.AlterField(
            model_name="revisionschedule",
            name="topic",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="revisions",
                to="api.topic",
            ),
        ),
    ]
