# Generated by Django 5.1.7 on 2025-10-25 01:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0006_alter_revision_topic_alter_revisionschedule_topic"),
    ]

    operations = [
        migrations.DeleteModel(
            name="Revision",
        ),
    ]
