# Generated by Django 5.1.7 on 2025-11-08 08:02

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0009_achievement_userstreak_userlevel_userachievement_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="PromoCode",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("code", models.CharField(db_index=True, max_length=50, unique=True)),
                ("code_hash", models.CharField(max_length=128, unique=True)),
                (
                    "tier",
                    models.CharField(
                        choices=[
                            ("tier1", "+25 Credits"),
                            ("tier2", "+50 Credits"),
                            ("tier3", "+100 Credits"),
                            ("unlimited", "Unlimited Credits"),
                        ],
                        max_length=20,
                    ),
                ),
                ("credits_granted", models.IntegerField()),
                ("grants_unlimited", models.BooleanField(default=False)),
                ("max_redemptions", models.IntegerField(default=1)),
                ("times_redeemed", models.IntegerField(default=0)),
                ("active", models.BooleanField(default=True)),
                ("expires_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name="CreditUsageLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "action",
                    models.CharField(
                        choices=[
                            ("initial", "Initial Credits"),
                            ("promo", "Promo Code Redemption"),
                            ("deduct", "AI Generation Used"),
                            ("admin_add", "Admin Added Credits"),
                            ("admin_remove", "Admin Removed Credits"),
                        ],
                        max_length=20,
                    ),
                ),
                ("credits_changed", models.IntegerField()),
                ("credits_after", models.IntegerField()),
                ("unlimited_before", models.BooleanField(default=False)),
                ("unlimited_after", models.BooleanField(default=False)),
                ("description", models.TextField(blank=True)),
                ("topic_id", models.IntegerField(blank=True, null=True)),
                ("promo_code_id", models.IntegerField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="credit_logs",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="UserCredit",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("available_credits", models.IntegerField(default=10)),
                ("total_credits_earned", models.IntegerField(default=10)),
                ("total_credits_used", models.IntegerField(default=0)),
                ("unlimited_access", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="credits",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="PromoCodeRedemption",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("credits_granted", models.IntegerField()),
                ("unlimited_granted", models.BooleanField(default=False)),
                ("redeemed_at", models.DateTimeField(auto_now_add=True)),
                ("ip_address", models.GenericIPAddressField(blank=True, null=True)),
                (
                    "promo_code",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="redemptions",
                        to="api.promocode",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="promo_redemptions",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-redeemed_at"],
                "unique_together": {("user", "promo_code")},
            },
        ),
    ]
