# Generated by Django 5.1.7 on 2026-01-17 12:39

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0011_userprofile"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="flashcard",
            name="times_postponed",
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name="flashcard",
            name="times_reviewed",
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name="flashcard",
            name="total_time_spent_seconds",
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name="flashcardrevisionschedule",
            name="completed_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="flashcardrevisionschedule",
            name="time_spent_seconds",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name="StudySession",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("started_at", models.DateTimeField(auto_now_add=True)),
                ("ended_at", models.DateTimeField(blank=True, null=True)),
                ("cards_reviewed", models.IntegerField(default=0)),
                ("cards_postponed", models.IntegerField(default=0)),
                ("total_time_seconds", models.IntegerField(default=0)),
                ("is_active", models.BooleanField(default=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="study_sessions",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-started_at"],
            },
        ),
    ]
